chain_width = 60
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true
format_macro_matchers = true
match_block_trailing_comma = true
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
