name: Publish to crates.io

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  publish:
    if: ${{ github.repository_owner == 'clechasseur' }} # Don't build on forks
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          toolchain: stable
          cache: false


      - name: Setup cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.17.9
        with:
          version: v1.17.9

      - name: Install required tools
        uses: clechasseur/rs-cargo@v5.0.6
        with:
          command: binstall
          args: -y just@1.48.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate to crates.io
        uses: rust-lang/crates-io-auth-action@c6f97d42243bad5fab37ca0427f495c86d5b1a18 # v1.0.5
        id: auth

      - name: Publish packages
        run: just publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
