name: Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-release-files:
    name: Build release files for ${{ matrix.arch }}-${{ matrix.platform }}
    if: github.repository_owner == 'clechasseur' # Don't build on forks
    strategy:
      fail-fast: false
      matrix:
        arch: [ aarch64, x86_64 ]
        platform: [ unknown-linux-gnu, apple-darwin, pc-windows-msvc ]
        include:
          - arch: universal
            platform: apple-darwin
          - os: ubuntu-24.04
          - platform: apple-darwin
            os: macos-15
          - platform: pc-windows-msvc
            os: windows-2025
          - crt-static: false
          - platform: pc-windows-msvc
            crt-static: true
        exclude:
          - arch: aarch64
            platform: unknown-linux-gnu
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        with:
          toolchain: stable
          cache: false

      - name: Setup cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@d62f33b587e73b0004731caebc7d2d46b18a7567 # v1.39.2
        with:
          target: ${{ matrix.arch }}-${{ matrix.platform }}

      - name: Set flag to link crt-static
        run: echo "RUSTFLAGS=${RUSTFLAGS} -C target-feature=+crt-static" >> ${GITHUB_ENV}
        if: ${{ matrix.crt-static }}

      - name: Build binaries and upload to GitHub release
        uses: taiki-e/upload-rust-binary-action@10c1cf6a3da113ad4e60018e386570529aa5f1d3 # v1.30.0
        with:
          bin: auxiliaire
          token: ${{ secrets.GITHUB_TOKEN }}
          archive: $bin-$target-$tag
          target: ${{ matrix.arch }}-${{ matrix.platform }}
          include: LICENSE,README.md
          leading-dir: true
