name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:

permissions:
  contents: read

jobs:
  create-release:
    name: Create draft release ${{ inputs.tag }}
    if: ${{ github.repository_owner == 'clechasseur' }} # Don't build on forks
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Create GitHub draft release
        uses: taiki-e/create-gh-release-action@v1.10.0
        with:
          draft: true

  build-release-files:
    name: Build release files for ${{ matrix.arch }}-${{ matrix.platform }}
    if: ${{ github.repository_owner == 'clechasseur' }} # Don't build on forks
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        arch: [ aarch64, x86_64 ]
        platform: [ unknown-linux-gnu, apple-darwin, pc-windows-msvc ]
        include:
          - os: ubuntu-24.04
          - platform: apple-darwin
            os: macos-15
          - platform: pc-windows-msvc
            os: windows-2025
          - crt-static: false
          - platform: pc-windows-msvc
            crt-static: true
          - arch: universal
            platform: apple-darwin
            os: macos-15
        exclude:
          - arch: aarch64
            platform: unknown-linux-gnu
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        with:
          toolchain: stable
          cache: false

      - name: Setup cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1.39.2
        with:
          target: ${{ matrix.arch }}-${{ matrix.platform }}

      - name: Set flag to link crt-static
        run: echo "RUSTFLAGS=${RUSTFLAGS} -C target-feature=+crt-static" >> ${GITHUB_ENV}
        if: ${{ matrix.crt-static }}

      - name: Build binaries and upload to GitHub release
        uses: taiki-e/upload-rust-binary-action@v1.30.0
        with:
          bin: auxiliaire
          token: ${{ secrets.GITHUB_TOKEN }}
          archive: $bin-$target-$tag
          target: ${{ matrix.arch }}-${{ matrix.platform }}
          include: LICENSE,README.md
          leading-dir: true
